### ISSUE TITLE
CI is failing now that logs are hosted on S3

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/NanosoldierReports#19]
Presumably the CI build script will need to be updated now that the logs are hosted on S3?

cc: @maleadt @staticfloat

**Comment by DilumAluthge** [comment]
Example log: https://travis-ci.com/github/JuliaCI/NanosoldierReports/builds/198269437

**Comment by maleadt** [comment]
Yes, I was waiting for a first daily run to get uploaded to S3 before adapting the scripts here.

That said, I was also considering removing the badges, since JuliaHub nowadays also has PkgEval badges... Thoughts?

**Comment by DilumAluthge** [comment]
Hmmm... when you click on a JuliaHub PkgEval badge, it just takes you to the JuliaHub page for that package.

In contrast, when you click on the PkgEval badges we have here, it brings you to the latest log so you can see why the job failed, which I find to be much more useful.

How about this:
1. We remove the part of the code that generates the badges. We can post on Discourse telling people that we will stop hosting badges, and that they should use the JuliaHub badges instead.
2. We keep the part of the code that redirects `https://juliaci.github.io/NanosoldierReports/pkgeval_badges/E/Example.html` to the latest daily log for Example.jl.

**Comment by DilumAluthge** [comment]
So that way we can tell people to use the PkgEval image from JuliaHub, but for the URL part of the badge, they can still use our URL, e.g. `https://juliaci.github.io/NanosoldierReports/pkgeval_badges/E/Example.html`
