### ISSUE TITLE
CI is broken?

### ISSUE THREAD

**Issue by simeonschaub** [JuliaCI/NanosoldierReports#25]
Looks like CI is broken, so the PkgEval badges last got updated on June 1st.

**Comment by maleadt** [comment]
Yeah, I'm not sure what's up, the actions started timing out without any obvious reason / change.

**Comment by simeonschaub** [comment]
Looks like it might be running out of disk space: https://github.com/JuliaCI/NanosoldierReports/actions/runs/935256813

**Comment by DilumAluthge** [comment]
What kind of clone do we do during the checkout step? We should make sure to do a shallow clone.

**Comment by simeonschaub** [comment]
Hmm, looks like it works again.
