### ISSUE TITLE
Link that brings you automatically to latest report for specific package

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/NanosoldierReports#5]
Currently the link:

https://juliaci.github.io/NanosoldierReports/pkgeval_badges/report.html

will always redirect to the latest report. This is great. But it brings you to the report for all packages. It would be really useful to have links that automatically redirect you to the latest report for `PackageA`. There would be one such link for every registered package.

cc: @maleadt

**Comment by maleadt** [comment]
There are no individual reports per packages, only raw logs. Linking to that wouldn't show you the parsed reason, which version of the package was compared against, etc.

**Comment by tkf** [comment]
For package authors, I think individual raw logs are more useful than the report aggregating the entire ecosystem.  For context: [[ANN] PkgDashboards - Community / Package announcements - JuliaLang](https://discourse.julialang.org/t/ann-pkgdashboards/34302)

**Comment by maleadt** [comment]
https://github.com/JuliaCI/NanosoldierReports/commit/fceda203d80cd83559a2bb294ccb730663a049f2
