### ISSUE TITLE
Failure due to permission denied

### ISSUE THREAD

**Issue by johnnychen94** [JuliaCI/NanosoldierReports#6]
* [Nanosoldier report (2020-03-10)](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_date/2020-03/10/logs/DemoCards/1.5.0-DEV-ff4f86714b.log) ❌ 
* [Github Action (2020-03-05)](https://github.com/johnnychen94/DemoCards.jl/runs/487499920) ✅ 

The failure is raised by https://github.com/johnnychen94/DemoCards.jl/blob/master/test/runtests.jl#L22-L25 , which is used to build complete documentation in the test stage.

Is there anything I can do to solve this?

**Comment by maleadt** [comment]
> Is there anything I can do to solve this?

Yes, your package writes files into its package directory, but when installing the package regularly those files and directories are read-only. Your github action checks out the package repository in the home folder, keeping everything writable.
